image: python:2.7.15

services:
  - mongo:latest

variables:
  MONGO_DATABASE: ipc_alert

stages:
  - init
  - build

init:
  stage: init
  script:
    - python -V

build:
  stage: build
  script:
    - echo 'Hello'
