# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:latest

services:
  #- mysql:latest
  #- postgres:latest
  - mongo:4.0.6

# This is a basic example for a gem or script which doesn't use
before_script:
  - whoami
  # - yum install gcc openssl-devel bzip2-devel
  # - wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz
  # - tar xzf Python-3.7.2.tgz
  # - cd Python-3.7.2
  # - ./configure --enable-optimizations
  # - make altinstall
  # # - rm /usr/src/Python-3.7.2.tgz
  # - python3.7 -V
  - python -V

stages:
  - init

init:
  stage: init
  script:
    - echo 'Testing'
  only:
    - branches
