# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:latest

services:
  #- mysql:latest
  #- postgres:latest
  - mongo:latest

variables:
  #POSTGRES_DB: database_name
  MONGO_DB: ipc_alert

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.cache/pip/

# This is a basic example for a gem or script which doesn't use
before_script:
  - python -V 
  - pip install -r requirements.txt

stages:
  - test

test:
  script:
  - echo 'Testing'
