image: python:latest

services:
  - mongo:latest

variables:
  MONGO_DATABASE: ipc_alert

stages:
  - init
  - build

init:
  stage: init
  script:
    - echo 'Build enviroment for testing'
    - python -V
    - pwd; /bin/cd /data/apiAlertServer/apiAlert/
    - source ../bin/activate
    - python -V

build:
  stage: build
  script:
    - echo 'Hello'
