# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:latest

services:
  - mongo:latest

variables:
  MONGODB_URI: 'mongodb://mongo:27017/api_alert'
# MONGO_INITDB_ROOT_USERNAME: root
# MONGO_INITDB_ROOT_PASSWORD: example

before_script:
  - pip install -r req.txt

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo 'Build'

first_test:
  stage: test
  script:
    - python manage.py test --pattern='register.py'
  environment:
    name: test
    url: https://test.example.com
  only:
    - branches
    - merge_requests

second_test:
  stage: test
  script:
    - python manage.py test --pattern='update.py'
  environment:
    name: test
    url: https://test.example.com
  only:
    - branches
    - merge_requests

third_test:
  stage: test
  script:
    - python manage.py test --pattern='active.py'
  environment:
    name: test
    url: https://test.example.com
  only:
    - branches
    - merge_requests

fourth_test:
  stage: test
  script:
    - python manage.py test --pattern='delete.py'
  environment:
    name: test
    url: https://test.example.com
  only:
    - branches
    - merge_requests

finally:
  stage: deploy
  script:
    - git branch
    - echo 'Finally'
  environment:
    name: deploy
    url: https://deploy.example.com
  only:
    - branches
    - merge_requests
