image: python:latest

services:
  - mongo:latest

variables:
  MONGO_DATABASE: ipc_alert

stages:
  - init
  - build

init:
  stage: init
  script:
    - apt-get install python-dev python2.7 gcc openssl-devel bzip2-devel
    - python -V
    - pip install -r req.txt

build:
  stage: build
  script:
    - echo 'Hello'
