# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:latest

services:
  - mongo:latest

variables:
  MONGODB_URI: 'mongodb://mongo:27017/api_alert'
# MONGO_INITDB_ROOT_USERNAME: root
# MONGO_INITDB_ROOT_PASSWORD: example

stages:
  - build
  - test
  - deploy
  - cleanup

build:
  stage: build
  script:
    - echo 'Build'

test:
  stage: test
  before_script:
    - apt-get update -qy
    - pip install -r req.txt
  script:
    - python manage.py test --pattern='register.py'
    - python manage.py test --pattern='update.py'
    - python manage.py test --pattern='active.py'
    - python manage.py test --pattern='delete.py'
  only:
    - merge_requests

staging:
  stage: deploy
  script:
    - apt-get update -qy
  only:
    - master
