# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:lastest

services:
  #- mysql:latest
  #- postgres:latest
  - mongo:latest

variables:
  PROJECT_PATH: /data/apiAlertServer/apiAlert/

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.cache/pip/

# This is a basic example for a gem or script which doesn't use
before_script:
  - pwd; sudo su
  - pwd; /bin/cd ${PROJECT_PATH}
  - pwd; source ../bin/activate
  - pwd; python -m pip --version

stages:
  - init

init:
  script:
    - echo 'Testing'
  only:
    - branches
