# Generated by Django 2.1.3 on 2018-12-03 08:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('schedule_uuid', models.UUIDField(editable=False)),
                ('serial', models.CharField(max_length=100)),
                ('start_time', models.TimeField(auto_now_add=True, null=True)),
                ('end_time', models.TimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('repeat_at', models.CharField(blank=True, max_length=255, null=True)),
                ('repeat_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
