# Generated by Django 2.1.3 on 2018-11-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_schedule_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ManyToManyField(related_name='schedule_user', to='users.Customer'),
        ),
    ]
